@startuml
class CompumatRepository {
    + <<async>> GetCompumat(id:int) : Task<Compumat>
    + <<async>> GetAllCompumats() : Task<List<Compumat>>
    + <<async>> CreateCompumat(compumat:Compumat) : Task<Compumat>
    + <<async>> UpdateCompumat(compumat:Compumat) : Task<Compumat>
    + <<async>> DeleteCompumat(id:string) : Task<string>
    - ParseCompumat(sqlDataReader:SqlDataReader) : Compumat
}
CompumatRepository o-> "sqlConnection" SqlConnection
@enduml
