@startuml
class MapRepository {
    + <<async>> GetMap(id:int) : Task<Map>
    + <<async>> GetAllMaps() : Task<List<Map>>
    + <<async>> CreateMap(map:Map) : Task<Map>
    + <<async>> UpdateMap(map:Map) : Task<Map>
    + <<async>> DeleteMap(id:string) : Task<string>
    - ParseMap(sqlDataReader:SqlDataReader) : Map
}
MapRepository o-> "sqlConnection" SqlConnection
@enduml
